### ISSUE TITLE
Add multilingual header navigation

### ISSUE THREAD

**Issue by horle** [Speyll/anemone#3]
Hi, first of all, I really like your theme! Thank you for this contribution :>

However, what I am really missing is multilingual support for the header navigation.
I tried adding `header_nav` in both the `[languages]` section and the following:
```
[extra]
languages = [ { ..., header_nav = ... } ]
```
but none is working.

Is there a way how to achieve this? Or could you maybe add this feature?

**Comment by Speyll** [comment]
Hello there! Apologies for the delayed response; I've been quite tied up lately, making it challenging to find time at my desktop. I'm thrilled to hear that you're enjoying the theme—it genuinely warms my heart.

And yes absolutely! I've gone ahead and implemented fully functional multi-language support into the theme (fingers crossed for flawless functionality, heh).

I've made some modifications to the `base.html` navigation section. Here's a snippet of what it looks like now:

```html
{% if config.extra.header_nav %}
<nav class="navBar">
   {% for nav_item in config.extra.header_nav %}
   {% set current_nav_item = nav_item[lang] %}
   {% if current_nav_item and current_nav_item.name %}
   <a href="{{ current_nav_item.url | safe }}" {% if current_nav_item.new_tab %}target="_blank" rel="noreferrer noopener"{% endif %}>{{ current_nav_item.name }}</a>
   {% endif %}
   {% endfor %}
</nav>
```

So now it allows us to have distinct header navigation menus tailored to different languages. To configure this, head over to the `config.toml` file and check for these settings:

```toml
[languages.en]
weight = 1
title = "anemone"
languageName = "English"
languageCode = "en"
relativeURL = false

[languages.fr]
weight = 2
title = "anemone"
languageName = "Français"
languageCode = "fr"
relativeURL = false

taxonomies = [
    {name = "tags", feed = true},
]


[extra]

[[extra.header_nav]]
en = { name = "/home/", url = "/" }
fr = { name = "/accueil/", url = "/fr" }

[[extra.header_nav]]
en = { name = "/about/", url = "/about" }
fr = { name = "/concernant/", url = "/about" }

[[extra.header_nav]]
en = { name = "/journal/", url = "/journal" }
fr = { name = "/journal/", url = "/journal" }

[[extra.header_nav]]
en = { name = "/blog/", url = "/blog" }
fr = { name = "/blog/", url = "/blog" }
```

The full `config.toml` with the added support, is on the main branch now, hope this helps!
