### ISSUE TITLE
How to set header_nav links for hosting in a domain subfolder?

### ISSUE THREAD

**Issue by UncleSamulus** [Speyll/anemone#7]
Hello, I am facing an issue with header_nav links: 
I added 
```toml
[[extra.header_nav]]
en = { name = "/home", url = "/" }
# fr = { name = "/accueil", url = "/fr" }

[[extra.header_nav]]
en = { name = "/about", url = "/about" }

[[extra.header_nav]]
en = { name = "/m1", url = "/m1" }
```
to my `config.toml` file, and uses zola build with `--base-url <my-subfolder>` option. 
The links with get_url works well, but those header_nav links does not use `get_url`, so it redirects me out of my zola website.
How could I correct this ?
I would like to avoid hard-coding the subfolder in the `url` value...

Thanks in advance
